### ISSUE TITLE
Automation when setting a label on PR

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormatConformance#121]
CI runs every time we change label. @DenizUgur I believe you wanted to start feature extraction that way, however sometimes we just want to set a label to a PR which has nothing to do with conformance file. e.g. I set enhancement label just to mark a PR. No need to run CI for this kind of thing. Is it an easy fix?

**Comment by DenizUgur** [comment]
Yes it is, the first step "changes" will still run but will skip others if it was just unrelated labeling
