### ISSUE TITLE
MP4Box dumps use decompressed version of the file

### ISSUE THREAD

**Issue by DenizUgur** [MPEGGroup/FileFormatConformance#142]
### Summary

The files under [compressed boxes](https://github.com/MPEGGroup/FileFormatConformance/tree/main/data/file_features/under_consideration/compressed_boxes) have decompressed versions of file dumps. All dumps should reflect the files as-is.

### Affected files

https://github.com/MPEGGroup/FileFormatConformance/tree/main/data/file_features/under_consideration/compressed_boxes

**Comment by jeanlf** [comment]
Done in https://github.com/gpac/gpac/commit/3241f7170e67246f6317eda43ab790c6147fe03c (add `-keep-comp` option)
