### ISSUE TITLE
[Website] Coverage percentage seems incorrect

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormatConformance#32]
### Summary

It's not clear how the coverage is computed:
![image](https://github.com/MPEGGroup/FileFormatConformance/assets/1830314/0bbd8573-188a-45cd-9b62-351a2ff0281d)

When I set the depth to 1, I end up with 142 boxes covered and 224 boxes not covered. I would expect to see a coverage percentage of 142/(142+224)~= 38.8% (instead of 63.39%). Same for depth=2, ...

The page should indicate the formula used to compute the coverage.

### Steps to reproduce

1. Open the Website
2. Go to coverage report
3. select a depth and compare the box numbers with the given percentage

**Comment by DenizUgur** [comment]
You are right. I think that just went over my head. The design of coverage page header needs some work for sure.

https://github.com/MPEGGroup/FileFormatConformance/blob/62936f54e42c78d719a94d226185795cbb45eb30/conformance-search/src/pages/CoveragePage.tsx#L97-L101
