### ISSUE TITLE
[Website] Link box name in coverage page to the box description

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormatConformance#33]
### Summary

It would be good to have the box names listed in the coverage tables linked to the other page that describes the box. You could click on a box (covered or not) and get a description for it.

### Steps to reproduce

1. Open the Website
2. Go to the coverage section
3. Find a box you're interested in (in the covered or not covered part), e.g. `mebx`
4. You should be able to click on it and it would take you to https://mpeggroup.github.io/FileFormatConformance/?query=mebx

**Comment by DenizUgur** [comment]
I assume adding a hyperlink for the last part of the path (bold box name) is sufficient?
