### ISSUE TITLE
[Website] The depth setting range is not large enough

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormatConformance#34]
### Summary

There remains red arrows in box lists, even when you put the max value in the depth range
![image](https://github.com/MPEGGroup/FileFormatConformance/assets/1830314/ddcc3232-c305-473c-9e96-a5ded1ec42c1)

Increase the slider max value to make sure it covers every possibility.

### Steps to reproduce

1. Open the coverage part
2. Set the slider to the max value

**Comment by DenizUgur** [comment]
The longest permutation we have has 11 box depth. I wanted to leave that setting within sensible limits. It can be increased for sure.
