### ISSUE TITLE
What is Restricted system 4CC `ress`?

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormatConformance#64]
https://github.com/MPEGGroup/FileFormatConformance/blob/2aefa1e1a865bea24c235c7a265da61db68a5c00/data/standard_features/14496-12/boxes.json#L1134C24-L1134C24

@cconcolato do you know what this is? @DenizUgur not so sure where it came from, do you remember?

**Comment by DenizUgur** [comment]
That was something we left for future Dimitri and Deniz to handle. AFAIK, specification was either not correct or had missing information

**Comment by DenizUgur** [comment]
`ress , `encs`, `rest`, and `resu` were the problematic ones

**Comment by podborski** [comment]
Found this table in the 8th edition draft of ISOBMFF:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">

Stream (Track) Type | Sample-Entry Code | SampleEntry Class
-- | -- | --
Video | resv | VisualSampleEntry
Audio | resa | AudioSampleEntry or AudioSampleEntryV1
Metadata | resm | MetaDataSampleEntry
Text | rest | SimpleTextSampleEntry
Subtitle | resu | XMLSubtitleSampleEntry
Systema | ress |  
Font | resf | FontSampleEntry
Haptics | resp | HapticSampleEntry
Volumetric visual | res3 | VolumetricVisualSampleEntry

</div></html>

The sample entry type for `ress` is not provided and I have no idea what it should be. Perhaps just a simple `SampleEntry`?

**Comment by DenizUgur** [comment]
Let me also not our findings from that time here:

`rest`: Syntax from ISOBMFF Table 8 seems to refer to wrong SampleEntry class. It should be PlainTextSampleEntry
`resu`: Probably it should be SubtitleSampleEntry
`ress`: Not clear
`encs`: See `rest`

**Comment by podborski** [comment]
Ah, it points to Part 14 

```cpp
aligned(8) class ESDBox 
	extends FullBox('esds', version = 0, 0) {
	ES_Descriptor	ES;
}
	// Visual Streams

class MP4VisualSampleEntry() extends VisualSampleEntry ('mp4v'){
	ESDBox	ES;
}
	// Audio Streams

class MP4AudioSampleEntry() extends AudioSampleEntry ('mp4a'){
	ESDBox ES;
}
	// all other Mpeg stream types
class MpegSampleEntry() extends SampleEntry ('mp4s'){
  ESDBox ES;
}
```

So I guess we can define `ress` having 3 types as shown above.

**Comment by DenizUgur** [comment]
That's fine, we just need to create new entries then

**Comment by podborski** [comment]
> rest: Syntax from ISOBMFF Table 8 seems to refer to wrong SampleEntry class. It should be PlainTextSampleEntry
> resu: Probably it should be SubtitleSampleEntry
I believe the question here is if it should be more generic. I'm not sure. I kind of suspect it should.

For example, There are 2 classes that derive from `SubtitleSampleEntry`

- `XMLSubtitleSampleEntry`
- `TextSubtitleSampleEntry`

but only `XMLSubtitleSampleEntry` is allowed to be encrypted / restricted? This was the reason why I thought it should be the base class.

> encs: See rest
It is similar to `ress`
