### ISSUE TITLE
video_cbcs_mkey_const_iv_subs* does not produce a valid XML. 

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormatConformance#74]
### Summary

ERROR: Couldn't parse "../data/file_features/under_consideration/cenc/video_cbcs_mkey_const_iv_subs.mp4". Not valid xml output from MP4Box.

This is probably a MP4Box bug.

### Affected files

- video_cbcs_mkey_const_iv_subs.mp4

**Comment by podborski** [comment]
@jeanlf this is most likely an issue with the MP4Box xml output but I didn't verify yet.

**Comment by jeanlf** [comment]
now fixed on master
