### ISSUE TITLE
ItemInfoBox version 2 is not defined

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormatConformance#9]
## Summary

Some files in the conformance suite have `version = 2` of the `ItemInfoBox` together with the `mif1` brand. 
Version 2 of the `ItemInfoBox` is not defined and is also not allowed by the `mif1` brand in HEIF.

## Steps to reproduce

1. Open a file
2. Parse `ItemInfoBox` `'iinf'`

## Affected specifications

- ISOBMFF
- HEIF

## Affected files

- [multilayer001.heic](https://conformance.mpeg.expert/ISOBMFF/published/heif/multilayer001.heic)
- [multilayer002.heic](https://conformance.mpeg.expert/ISOBMFF/published/heif/multilayer002.heic)
- [multilayer004.heic](https://conformance.mpeg.expert/ISOBMFF/published/heif/multilayer004.heic)
- [multilayer005.heic](https://conformance.mpeg.expert/ISOBMFF/published/heif/multilayer005.heic)

**Comment by EthanXzhang** [comment]
Find another closed issue for the some problem.
https://github.com/nokiatech/heif_conformance/issues/7
Its seem its a bug version for heif encoder to generate a version=2 iinf for HEIF?

**Comment by podborski** [comment]
@EthanXzhang, yes. This is correct. Those files needs to be re-submitted to the conformance suite. After that we can close this issue.

**Comment by podborski** [comment]
@lassehe can you bring an input contribution to MPEG next meeting on the updates you mention in https://github.com/nokiatech/heif_conformance/issues/7

**Comment by podborski** [comment]
Contributed files from [m67810](https://dms.mpeg.expert/doc_end_user/current_document.php?id=92989) match the fixes we did initially.
