### ISSUE TITLE
"Files under consideration"

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormatConformance#91]
### Summary

We should consider removing the notion of "Files under consideration". 
I think files should be reviewed when the contribution is received, and when the PR is prepared. We can always correct them afterwards if we see bugs. 
This would mean removing the "Files under consideration" from the main page, and renaming "Files submitted" into "Conformance files" 

### Steps to reproduce

N/A

**Comment by DenizUgur** [comment]
Additionally, we would need to remove the related statistics on coverage page.

As a suggestion, we could instead show open PR count on home page in place of "files under consideration" if it makes sense
