### ISSUE TITLE
Issue generating *_gpac.json files

### ISSUE THREAD

**Issue by LionelTocze** [MPEGGroup/FileFormatConformance#99]
I try to use the https://github.com/MPEGGroup/FileFormatConformance/commit/897c4dc10d5505d329552c6657767b43d8d5ee75 to check some test vector, and have the following issues :
 - from the several **mp4** files, only one was taken into account
 - it require to put the directory with the test vectors under **data/file_features** directory, which was not previously the case : Is it correct ?

I then checkout the commit 2dcb214bd1f55798cee1258c830e9e680b71f6ed, where the two previous issues are no more present. However, the ***_gpac.json** files are no more generated. I fix this by modifying code 

  https://github.com/MPEGGroup/FileFormatConformance/blob/2dcb214bd1f55798cee1258c830e9e680b71f6ed/src/feature_extractor/file_features.py#L466 
 
replacing *actual_file_path_* by *mp4_path*. This modification may also be necessary in main branch.

**Comment by LionelTocze** [comment]
Hi,
I used the following command, from *src* directory
`poetry run contribute-files -i Files_Directory`

I will run (later) the command for extracting files feature only, and will update this issue with result of testing this command.

**Comment by LionelTocze** [comment]
Hi again,
I just test the 2 following commands with success:
`poetry run extract-file-features -d 'Test2/*.mp4'`
and
`poetry run  contribute-files -i '../data/file_features/Test2/`

I still have some questions:
- command with *contribute-files*, requires test vectors to be in a directory under data/files_features : Correct ? (Command with *extract-file-features* has not this constraint.)
- Both commands try access to some http resources, (So could failed if behind a proxy and incorrect settings of proxy environment.) : Is it mandatory or could it be bypassed.

**Comment by DenizUgur** [comment]
> * command with _contribute-files_, requires test vectors to be in a directory under data/files_features : Correct ? (Command with _extract-file-features_ has not this constraint.)

That's true. What we do is under `data/file_features` there would be a `under_consideration` folder. In which we create new folder for the contribution you are making. See this simple [example](https://github.com/MPEGGroup/FileFormatConformance/pull/82/files).

> * Both commands try access to some http resources, (So could failed if behind a proxy and incorrect settings of proxy environment.) : Is it mandatory or could it be bypassed.

The only request we make is the get the data from [MP4RA](https://mp4ra.org/) and this is bypassed if you contribution was under `under_consideration` folder like I mentioned above.
